### ISSUE TITLE
Feedback on interface strings

### ISSUE THREAD

**Issue by TicClick** [naseweis520/osu-Sync#10]
- Titles should never end with a period. Besides the titles, this also goes for:
  - Checkbox labels and any labels in general (including buttons);
  - Window titles;
  - Dropdown list items;
  - Status messages ("Please sync." and so forth).
- "Get Beatmap Sets" is unclear, perhaps it should be "Sync" since you're asking a user to sync everywhere else.
- Using the same string "Installed" for both category's name and status label ("Installed?") is not really good, wording of these two may differ among the languages.
- I have a strange feeling I see your application's name way too often when browsing the interface, consider reducing its usage to main window's title and one or two occurences in "About".
- In Updater window, there's "version" word popping up too often.  
- Finally, see my note on Approved category: https://crowdin.com/translate/osusync/3/en-ru#q=approved

**Comment by muekoeff** [comment]
- "Get Beatmap Sets" is unclear, perhaps it should be "Sync" since you're asking a user to sync everywhere else.
  - Done.
- Using the same string "Installed" for both category's name and status label ("Installed?") is not really good, wording of these two may differ among the languages.
  - Do you have a suggestion on how to call it instead? _Edit:_ Maybe "Overview"?
- I have a strange feeling I see your application's name way too often when browsing the interface, consider reducing its usage to main window's title and one or two occurences in "About".
  - Reduced from 24 occurrences to 15 ones.

**Comment by muekoeff** [comment]
- Titles should never end with a period.
  - Partially changed.
- In Updater window, there's "version" word popping up too often.
  - Ok, sometimes replaced with "Update".

**Comment by TicClick** [comment]
"Overview", "Your maps", anything of that sort, yeah.

**Comment by muekoeff** [comment]
- "Overview", "Your maps", anything of that sort, yeah.
  - Set to "Overview".
- Finally, see my note on Approved category: https://crowdin.com/translate/osusync/3/en-ru#q=approved
  - "Approved" will be displayed as "Ranked"
