### ISSUE TITLE
Download Server

### ISSUE THREAD

**Issue by Kontorted** [naseweis520/osu-Sync#44]
Why not use the osu default server?

**Comment by muekoeff** [comment]
osu!Sync uses only third party mirrors since the official download server requires the user to be authenticated (i.e. logged in). In order to provide this the application would have to request the user to login to osu! inside of osu!Sync and would have to store all cookies associated with the login, possibly store them and use them for every download.

Theoretically this is possible and not even that hard to implement. However, I don't know whether peppy would be pleased by this attempt to abuse his protection.

If this answers your question then please close this issue.

**Comment by Kontorted** [comment]
What about the API access key that can be stored within the application? Hasnt it been written to give third-party applications access?

**Comment by muekoeff** [comment]
I don't think that there's an endpoint for actually authorising downloads (cf. https://github.com/ppy/osu-api/wiki).
The API is currently used for requesting meta data of beatmaps.
